"""添加 reference_type 列到 transactions 表

Revision ID: d4c745cb31ca
Revises: 0e2fd7519ab0
Create Date: 2025-05-09 20:30:35.150276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c745cb31ca'
down_revision = '0e2fd7519ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('reference_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'reference_type')
    # ### end Alembic commands ###
